nevermined-io/tools

.github/workflows/release-github.yml, README.md, compose-files/commons.yml, compose-files/dashboard.yml, compose-files/events_handler.yml, compose-files/faucet.yml, compose-files/gateway.yml, compose-files/metadata.yml, compose-files/metadata_elasticsearch.yml, compose-files/metadata_mongodb.yml, compose-files/nevermined_contracts.yml, compose-files/nodes/ganache_node.yml, compose-files/nodes/integration_node.yml, compose-files/nodes/production_node.yml, compose-files/nodes/spree_node.yml, compose-files/nodes/staging_node.yml, compose-files/secret_store.yml, compose-files/secret_store_signing_node.yml, start_nevermined.sh
Adding names to docker images and fixing text
nope
=> Adding names to docker images and fixing text

README.md, compose-files/cli.yml, start_nevermined.sh
This PR adds the Nevermind CLI to the components run by nevermined-tools
https://github.com/keyko-io/nevermined-tools/issues/7
=> Adding nevermined-cli to the loop

scripts/setup_minikube.sh
- Updated `setup_minikube.sh` to install argo-artifacts with minio during argo installation
=> Added minio to argo installation

scripts/setup_minikube.sh
Just added permissions that seemed to be missing so that we can access to argo web interface.
=> Added k8s permissions to access the argo web interface

README.md, compose-files/dashboard.yml, start_nevermined.sh
Now they can be enabled using the flags `--dashboard` or `--events-handler`
=> Disabling the dashboard and events handler by default.

scripts/setup_minikube.sh
=> Fixing some minikube installation

compose-files/gateway.yml, scripts/compute-api-deployment.yaml, scripts/constants.rc, scripts/setup_minikube.sh, scripts/wait_for_migration_keeper_artifacts.sh, start_nevermined.sh
- Start the compute-api in minikube instead of docker-compose
- Start for artifacts before creating artifacts volume
- Wait for services to be ready before port forwarding
Resolves https://github.com/keyko-io/nevermined-compute-api/issues/24
=> Integrated compute stack with nevermined-tools

scripts/setup_minikube.sh, scripts/wait_for_compute_api.sh, start_nevermined.sh
- Make host docker credentials available to k8s as a secret
- Added a script to wait for the compute api to be online (since it's the last service to start)
- Make sure k8s is running before using helm
- Fixed an issue when starting argo artifacts
=> Use docker host credentials

compose-files/gateway.yml
Changes to make run new name of the gateway env var for compute-api-url
=> Update to the new compute-api env variable in the gateway

scripts/wait_for_compute_api.sh
Increment timeout that was making fail actions sometimes
=> Increment timeout waiting for the compute api

compose-files/faucet.yml
Fix small bug in the fauce image name.
=> fix wrong image in faucet compose

ACL/ldap/data/200-user-alice.ldif, ACL/ldap/data/201-user-bob.ldif, ACL/ldap/data/202-user-john.ldif, ACL/ldap/schema/100-group-sales.ldif, ACL/ldap/schema/101-group-people.ldif, ACL/ldap/schema/102-group-finance.ldif, ACL/ldap/schema/103-group-external.ldif, README.md, compose-files/openldap.yml, docs/openldap.md, scripts/constants.rc, scripts/wait_for_openldap.sh, start_nevermined.sh
This PR includes the changes to automate the data loading of a simple hierarchy of users and groups. More info can be found in the docs/openldap.md file
=> Adding support to OpenLdap

scripts/wait_for_openldap.sh
- disable bash exit on error when checking for openldap status
- `-it` flag of docker exec does not work well in bash scripts
=> Small fixes to wait_for_openldap script

scripts/wait_for_openldap.sh
Hopefully this should fix the ldap problem in the CI
=> use curl instead of netcat

compose-files/secret_store.yml, networks/secret-store/config/config.toml.save, start_nevermined.sh
Reverts nevermined-io/tools#21
=> Revert "update to the last version of secret store"

scripts/wait_for_service.sh
=> Added script to wait for any service. To be used in CI

scripts/setup_minikube.sh
- Replaces a deprecated helm repo for argo-artifacts
=> Fixed helm error about deprecated charts

compose-files/nodes/spree_node.yml, start_nevermined.sh
Added --spree-embedded-contracts cmdline option
nevermined-io/internal#124
=> Added --spree-embedded-contracts cmdline option

compose-files/control_center_backend.yml, start_nevermined.sh
To run it the flag `--control-center` is need it. In the future this flag should make available the frontend as well.
=> Add compose for the control center backend

compose-files/control_center_backend.yml, compose-files/control_center_ui.yml, start_nevermined.sh
This add the control center ui component into the nevermined tools.
Close https://github.com/nevermined-io/control-center-backend/issues/2
=> Adding control center ui

start_nevermined.sh
- Update to the latest version of the components
- use KEEPER_VERSION for the docker tag when using `--spree-embedded-contracts`
=> Update to the latest version of the components

scripts/setup_minikube.sh, start_nevermined.sh
Remove contracts of the other networks to avoid have an issue in the config map creation.
=> Add script that removes contracts that are not need it

scripts/setup_minikube.sh
=> Try without quotes

scripts/setup_minikube.sh
=> fix script

scripts/setup_minikube.sh, scripts/wait_for_migration_keeper_artifacts.sh
=> Test commenting the configmap

README.md, compose-files/bazaart.yml, start_nevermined.sh
- Added bazaart to nevermined-tools that is disabled by default and can be started by passing `--bazaart` to `start_nevermined.sh`
Resolves https://github.com/nevermined-io/cryptoarts/issues/36
=> Added bazaart to nevermined-tools

compose-files/control_center_backend.yml, scripts/register_services.sh, start_nevermined.sh
Registering services in the control center.
=> Register control panel service at the beginning

compose-files/elasticsearch.yml
Upgraded to the latest version of elasticsearch
Resolves https://github.com/nevermined-io/internal/issues/151
=> Upgrade to latest version of elasticsearch

scripts/setup_minikube.sh
Update minio chart memory request from 4Gi to 1Gi so it can start in minikube envs.
=> Update minio chart memory request

scripts/setup_minikube.sh, start_nevermined.sh
=> Update minikube and kubectl to latest version

.github/workflows/test.yml, README.md
- Added tests to the CI
- Added badge to README
=> Added CI tests

scripts/setup_minikube.sh, start_nevermined.sh
- Install argo using the helm chart (with kubernetes apply it wasn't working correctly)
- Force minikube to use the docker driver and host networking (networking changes based on the driver used)
Related to Issue https://github.com/nevermined-io/internal/issues/148
=> Several fixes to argo and the compute stack

README.md
=> Add get started for mac section, fix md warnings

README.md, compose-files/minio.yml, start_nevermined.sh
=> Added --minio flag to start minio

compose-files/bazaart.yml, start_nevermined.sh
- Small configuration fixes for bazaart
=> Small fixes to bazaart settings

start_nevermined.sh
=> Disable arweave

README.md, compose-files/graph.yml, start_nevermined.sh
This adds a graph node to nevermined tools and dependencies (ipfs node, postgres)
Resolves #79
=> Added graph node to nevermined-tools

README.md, start_nevermined.sh
=> Pinning to the last stable versions and removing the old CLI

README.md
Add note about ips in MacOS
Related to Issue #82
=> Add note about ips in MacOS

compose-files/graph.yml
=> Updated graph-node

compose-files/graph.yml, start_nevermined.sh
Added the graph to nevermined-tools
=> Make graph start by default with tools

compose-files/gateway.yml, start_nevermined.sh
=> Set ESTUARY_GATEWAY env

compose-files/nodes/geth_localnet.yml
=> fix docker-compose typo

compose-files/nodes/ganache_node.yml, start_nevermined.sh
Reverts nevermined-io/tools#110
=> Revert "Set rpc port"

.github/workflows/test.yml, scripts/wait-subgraphs.sh, start_nevermined.sh
=> set keeper version to latest

scripts/wait-subgraphs.sh
Related to Issue https://github.com/nevermined-io/subgraph/issues/43
=> fix script to wait for subgraph

compose-files/gateway_new.yml, start_nevermined.sh
=> Adding support for new gateway

compose-files/gateway_new.yml, compose-files/nodes/geth_localnet.yml, compose-files/nodes/polygon_localnet.yml, compose-files/nodes/spree_node.yml, start_nevermined.sh
=> Handling circuits directory

start_nevermined.sh
=> small fix for now for the marketplace-api

start_nevermined.sh
=> revert back to using latest marketplace-api

compose-files/opengsn.yml, start_nevermined.sh
=> starting opengsn server

scripts/setup_compute_stack.sh
=> using `kubectl` alias to avoid failures with `minikube`

scripts/setup_compute_stack.sh
Fix minikube issues with MacOs
Fix argo authentication issues
=> Fix issues with argo auth and macos stuff
